# Generated by Django 3.0.6 on 2020-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueBuzzer', '0002_auto_20201024_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='point',
            name='logoImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
