# Generated by Django 3.0.6 on 2020-10-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queueBuzzer', '0003_auto_20201024_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointowner',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointowner',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueBuzzer.Point'),
        ),
    ]
