spring:
  datasource:
    url: jdbc:h2:mem:queuBuzzerDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  #    platform:
  #      h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  security:
    user:
      name:
        admin
      password:
        '{noop}admin'